name: tests

on:
  pull_request:
  push:
    branches: [main]

env:
  DRIVER_TOKEN: github-actions
  TOX_PARALLEL_NO_SPINNER: 1

jobs:
  tox:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.cache/pre-commit
            .tox
            .mypy_cache
            .coverage
            ${{ env.pythonLocation }}
          key: ${{ runner.os }}-${{ env.pythonLocation }}-pip-${{ hashFiles('**/requirements-tox.txt') }}
      - name: Install dependencies
        run: python -m pip install --progress-bar off tox
      - name: Run all envs
        run: tox -p auto -e 'libcloud{30,31,32,33,34,35,36},pre-commit,coverage'
